api:
  image:
    repository: template-monorepo-ts/api
    tag: prod
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
    - host: api.domain.local
      paths:
      - path: /api/
        pathType: Prefix

docs:
  image:
    repository: template-monorepo-ts/docs
    tag: prod
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
    - host: doc.domain.local
      paths:
      - path: /
        pathType: Prefix
