{{- if .Values.mcp.enabled -}}
{{- if or .Values.mcp.envSecret .Values.global.envSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "mcp" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "mcp")) | nindent 4 }}
data:
  {{- if .Values.global.envSecret -}}
  {{- include "helper.secret" .Values.global.envSecret | indent 2 }}
  {{- end -}}
  {{- if .Values.mcp.envSecret -}}
  {{- include "helper.secret" .Values.mcp.envSecret | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end -}}
