{{- if or .Values.docs.env .Values.global.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "docs" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "docs")) | nindent 4 }}
data:
  {{- if .Values.global.env -}}
  {{- include "helper.env" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.docs.env -}}
  {{- include "helper.env" .Values.docs | indent 2 }}
  {{- end -}}
{{- end -}}
