{{- if .Values.docs.container.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "template.docs.fullname" . }}
  labels: {{- include "template.docs.labels" . | nindent 4 }}
data: {{- include "template.containerEnv" .Values.docs.container | indent 2 }}
{{- end -}}
