{{- if or .Values.docs.env .Values.global.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "template.docs.fullname" . }}
  labels: {{- include "template.docs.labels" . | nindent 4 }}
data:
  {{- if .Values.global.env -}}
  {{- include "template.env" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.docs.env -}}
  {{- include "template.env" .Values.docs | indent 2 }}
  {{- end -}}
{{- end -}}
