{{- if and .Values.docs.imageCredentials.username .Values.docs.imageCredentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template.docs.fullname" . }}-pullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "template.docs.imagePullSecret" . }}
{{- end }}
