{{- if .Values.docs.container.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "template.docs.fullname" . }}
  labels: {{- include "template.docs.labels" . | nindent 4 }}
data: {{- include "template.containerSecret" .Values.docs.container | indent 2 }}
{{- end -}}
