apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template.docs.fullname" . }}
  labels:
    {{- include "template.docs.labels" . | nindent 4 }}
data:
  {{- include "template.containerSecret" .Values.docs.container | nindent 2 }}
