{{- if or .Values.docs.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "template.docs.fullname" . }}
  labels: {{- include "template.docs.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "template.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.docs.secrets -}}
  {{- include "template.secret" .Values.docs | indent 2 }}
  {{- end -}}
{{- end -}}
