{{- if or .Values.docs.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "docs" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "docs")) | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "helper.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.docs.secrets -}}
  {{- include "helper.secret" .Values.docs | indent 2 }}
  {{- end -}}
{{- end -}}
