{{- if .Values.docs.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template.docs.serviceAccountName" . }}
  labels: {{- include "template.docs.labels" . | nindent 4 }}
  {{- with .Values.docs.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
