{{- if and .Values.docs.serviceAccount.enabled .Values.docs.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.docs.serviceAccount.name | default (printf "%s-%s" (include "helper.fullname" .) "docs") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "docs")) | nindent 4 }}
  {{- if .Values.docs.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .Values.docs.serviceAccount.annotations) . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.docs.serviceAccount.automountServiceAccountToken }}
{{- end }}
