{{- if .Values.docs.statefulset }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "docs" | trunc 63 | trimSuffix "-" }}
  labels: {{- include "helper.labels" (dict "root" . "componentName" "docs") | nindent 4 }}
spec:
  {{- if not .Values.docs.autoscaling.enabled }}
  replicas: {{ .Values.docs.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "docs") | nindent 6 }}
  serviceName: {{ printf "%s-%s" (include "helper.fullname" .) "docs" | trunc 63 | trimSuffix "-" }}
  template:
    metadata:
      {{- if or .Values.docs.podAnnotations .Values.docs.secrets .Values.docs.env .Values.global.env .Values.global.secrets }}
      annotations:
        {{- include "helper.checksum" (list $ "/docs/configmap.yaml") | nindent 8 }}
        {{- include "helper.checksum" (list $ "/docs/secret.yaml") | nindent 8 }}
        {{- if .Values.docs.podAnnotations }}
        {{- toYaml .Values.docs.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels: {{- include "helper.labels" (dict "root" . "componentName" "docs") | nindent 8 }}
        {{- if .Values.docs.podLabels }}
        {{- toYaml .Values.docs.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.docs.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.docs.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if (get .Values "docs").serviceAccount.enabled }}
      serviceAccountName: {{ .Values.docs.serviceAccount.name | default (printf "%s-%s" (include "helper.fullname" .) "docs" | trunc 63 | trimSuffix "-") }}
      {{- end }}
      {{- if .Values.docs.podSecurityContext }}
      securityContext: {{- toYaml .Values.docs.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.docs.initContainers }}
      initContainers: {{- tpl (toYaml .Values.docs.initContainers) . | nindent 6 }}
      {{- end }}
      containers:
      - name: docs
        {{- if .Values.docs.securityContext }}
        securityContext: {{- toYaml .Values.docs.securityContext | nindent 10 }}
        {{- end }}
        image: "{{ .Values.docs.image.repository }}:{{ .Values.docs.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.docs.image.pullPolicy }}
        {{- if .Values.docs.command }}
        command:
        {{- range .Values.docs.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.docs.args }}
        args:
        {{- range .Values.docs.args }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.docs.contrainerPort }}
          protocol: TCP
        {{- if .Values.docs.extraPorts }}
          {{- toYaml .Values.docs.extraPorts | nindent 8 }}
        {{- end }}
        {{- if or .Values.docs.env .Values.global.env .Values.global.secrets .Values.docs.envFrom }}
        envFrom:
        {{- if or .Values.docs.env .Values.global.env }}
        - configMapRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "docs" | trunc 63 | trimSuffix "-" }}
        {{- end }}
        {{- if or .Values.docs.secrets .Values.global.secrets }}
        - secretRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "docs" | trunc 63 | trimSuffix "-" }}
        {{- end }}
        {{- if .Values.docs.envFrom }}
          {{- toYaml .Values.docs.envFrom | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.docs.probes.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.docs.probes.healthcheck.path }}
            port: {{ .Values.docs.probes.healthcheck.port | default .Values.docs.contrainerPort }}
          initialDelaySeconds: {{ .Values.docs.probes.startupProbe.initialDelaySeconds }}
          successThreshold: {{ .Values.docs.probes.startupProbe.successThreshold }}
          failureThreshold: {{ .Values.docs.probes.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.docs.probes.startupProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.docs.probes.startupProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.docs.probes.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.docs.probes.healthcheck.path }}
            port: {{ .Values.docs.probes.healthcheck.port | default .Values.docs.contrainerPort }}
          initialDelaySeconds: {{ .Values.docs.probes.readinessProbe.initialDelaySeconds }}
          successThreshold: {{ .Values.docs.probes.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.docs.probes.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.docs.probes.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.docs.probes.readinessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.docs.probes.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.docs.probes.healthcheck.path }}
            port: {{ .Values.docs.probes.healthcheck.port | default .Values.docs.contrainerPort }}
          initialDelaySeconds: {{ .Values.docs.probes.livenessProbe.initialDelaySeconds }}
          successThreshold: {{ .Values.docs.probes.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.docs.probes.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.docs.probes.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.docs.probes.livenessProbe.timeoutSeconds }}
        {{- end }}
        resources: {{- toYaml .Values.docs.resources | nindent 10 }}
        {{- if .Values.docs.volumeMounts }}
        volumeMounts: {{- toYaml .Values.docs.volumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.docs.extraContainers }}
        {{- tpl (toYaml .Values.docs.extraContainers) . | nindent 6 }}
      {{- end }}
      {{- if .Values.docs.hostAliases }}
      hostAliases: {{- toYaml .Values.docs.hostAliases | nindent 6 }}
      {{- end }}
      {{- if .Values.docs.nodeSelector }}
      nodeSelector: {{- toYaml .Values.docs.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.docs.affinity }}
      affinity: {{- toYaml .Values.docs.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.docs.tolerations }}
      tolerations: {{- toYaml .Values.docs.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.docs.volumes }}
      volumes: {{- toYaml .Values.docs.volumes | nindent 6 }}
      {{- end }}
  {{- if .Values.docs.volumeClaims }}
  volumeClaimTemplates: {{- toYaml .Values.docs.volumeClaims | nindent 2 }}
  {{- end }}
{{- end }}
