version: '3.9'

services:
  api:
    restart: always
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
      target: dev
    image: template-monorepo-ts/api:dev
    container_name: template-monorepo-ts_api
    ports:
      - 8081:8081
    volumes:
      - ../apps/api:/app/apps/api
    networks:
      - template-monorepo-ts-network

  docs:
    restart: always
    build:
      context: ..
      dockerfile: apps/docs/Dockerfile
      target: dev
    image: template-monorepo-ts/docs:dev
    container_name: template-monorepo-ts_docs
    ports:
      - 8082:8082
    volumes:
      - ../apps/docs:/app/apps/docs
    networks:
      - template-monorepo-ts-network

networks:
  template-monorepo-ts-network:
    driver: bridge
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
