services:
  api:
    image: template-monorepo-ts/api:dev
    container_name: template-monorepo-ts_api
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
      target: dev
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: always
    working_dir: /app
    ports:
    - 8081:8081
    env_file:
    - ../apps/api/.env.docker
    environment:
    - OTEL_SERVICE_NAME=api
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    develop:
      watch:
      - action: sync
        path: ../apps/api
        target: /app/apps/api
        ignore:
        - node_modules/
      - action: sync
        path: ../packages/shared
        target: /app/packages/shared
        ignore:
        - node_modules/
      - action: rebuild
        path: package.json
    networks:
    - template-monorepo-ts-network

  docs:
    image: template-monorepo-ts/docs:dev
    container_name: template-monorepo-ts_docs
    build:
      context: ..
      dockerfile: apps/docs/Dockerfile
      target: dev
    restart: always
    working_dir: /app
    ports:
    - 8082:8082
    volumes:
    - ../apps/docs:/app/apps/docs
    networks:
    - template-monorepo-ts-network

  db:
    image: docker.io/postgres:17.6
    container_name: template-monorepo-ts_postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: template-monorepo-ts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
    - template-monorepo-ts-data-dev:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U admin -d template-monorepo-ts
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - template-monorepo-ts-network
    attach: false

  migrate:
    image: template-monorepo-ts/api:migrate
    container_name: template-monorepo-ts_migrate
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
      target: migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
    - API__DB_URL=postgresql://admin:admin@db:5432/template-monorepo-ts?schema=public
    networks:
    - template-monorepo-ts-network
    restart: no

  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.146.1
    container_name: template-monorepo-ts_otel-collector
    restart: always
    volumes:
    - ./otel/collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
    - 4317:4317
    - 4318:4318
    networks:
    - template-monorepo-ts-network

  tempo:
    image: docker.io/grafana/tempo:2.10.1
    container_name: template-monorepo-ts_tempo
    restart: always
    volumes:
    - ./otel/tempo.yaml:/etc/tempo.yaml
    command:
    - -config.file=/etc/tempo.yaml
    networks:
    - template-monorepo-ts-network

  prometheus:
    image: docker.io/prom/prometheus:v3.5.1
    container_name: template-monorepo-ts_prometheus
    restart: always
    volumes:
    - ./otel/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
    - template-monorepo-ts-network

  grafana:
    image: docker.io/grafana/grafana:11.6.11
    container_name: template-monorepo-ts_grafana
    restart: always
    ports:
    - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    volumes:
    - ./otel/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    - ./otel/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    - ./otel/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
    - template-monorepo-ts-network

volumes:
  template-monorepo-ts-data-dev:

networks:
  template-monorepo-ts-network:
    driver: bridge
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
