services:
  api:
    image: template-monorepo-ts/api:dev
    container_name: template-monorepo-ts_api
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
      target: dev
    restart: always
    ports:
    - 8081:8081
    env_file:
    - ../apps/api/.env.docker
    develop:
      watch:
      - action: sync
        path: ../apps/api
        target: /app/apps/api
        ignore:
        - node_modules/
      - action: sync
        path: ../packages/shared
        target: /app/packages/shared
        ignore:
        - node_modules/
      - action: rebuild
        path: package.json
    networks:
    - template-monorepo-ts-network

  docs:
    restart: always
    build:
      context: ..
      dockerfile: apps/docs/Dockerfile
      target: dev
    image: template-monorepo-ts/docs:dev
    container_name: template-monorepo-ts_docs
    ports:
    - 8082:8082
    volumes:
    - ../apps/docs:/app/apps/docs
    networks:
    - template-monorepo-ts-network

  db:
    restart: always
    image: docker.io/bitnami/postgresql:16.4.0
    container_name: template-monorepo-ts_postgres
    environment:
      POSTGRESQL_DATABASE: template-monorepo-ts
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - template-monorepo-ts-data-prod:/bitnami/postgresql
    networks:
      - template-monorepo-ts-network
    attach: false

volumes:
  template-monorepo-ts-data-prod:

networks:
  template-monorepo-ts-network:
    driver: bridge
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
