{{- if not .Values.web.statefulset }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "web" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "web")) | nindent 4 }}
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.web.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "web") | nindent 6 }}
  strategy:
    type: {{ .Values.web.strategy.type }}
    {{- if eq .Values.web.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.web.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.web.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      {{- if or .Values.web.podAnnotations .Values.web.secrets .Values.web.env .Values.global.env .Values.global.secrets }}
      annotations:
        {{- include "helper.checksum" (list $ "/web/configmap.yaml") | nindent 8 }}
        {{- include "helper.checksum" (list $ "/web/secret.yaml") | nindent 8 }}
        {{- if .Values.web.podAnnotations }}
        {{- toYaml .Values.web.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels: {{- include "helper.labels" (dict "root" . "componentName" "web") | nindent 8 }}
        {{- if .Values.web.podLabels }}
        {{- toYaml .Values.web.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.web.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.web.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if (get .Values "web").serviceAccount.enabled }}
      serviceAccountName: {{ .Values.web.serviceAccount.name | default (printf "%s-%s" (include "helper.fullname" .) "web") }}
      {{- end }}
      {{- if .Values.web.podSecurityContext }}
      securityContext: {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.web.initContainers }}
      initContainers: {{- tpl (toYaml .Values.web.initContainers) . | nindent 6 }}
      {{- end }}
      containers:
      - name: web
        {{- if .Values.web.securityContext }}
        securityContext: {{- toYaml .Values.web.securityContext | nindent 10 }}
        {{- end }}
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        {{- if .Values.web.command }}
        command:
        {{- range .Values.web.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.web.args }}
        args:
        {{- range .Values.web.args }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.web.containerPort }}
          protocol: TCP
        {{- if .Values.web.extraPorts }}
          {{- toYaml .Values.web.extraPorts | nindent 8 }}
        {{- end }}
        {{- if or .Values.web.env .Values.global.env .Values.global.secrets .Values.global.secrets .Values.web.envFrom }}
        envFrom:
        {{- if or .Values.web.env .Values.global.env }}
        - configMapRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "web" }}
        {{- end }}
        {{- if or .Values.web.secrets .Values.global.secrets }}
        - secretRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "web" }}
        {{- end }}
        {{- if .Values.web.envFrom }}
          {{- toYaml .Values.web.envFrom | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.web.probes.startupProbe }}
        startupProbe: {{- toYaml .Values.web.probes.startupProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.web.probes.readinessProbe }}
        readinessProbe: {{- toYaml .Values.web.probes.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.web.probes.livenessProbe }}
        livenessProbe: {{- toYaml .Values.web.probes.livenessProbe | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.web.resources | nindent 10 }}
        {{- if .Values.web.volumeMounts }}
        volumeMounts: {{- toYaml .Values.web.volumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.web.extraContainers }}
        {{- tpl (toYaml .Values.web.extraContainers) . | nindent 6 }}
      {{- end }}
      {{- if .Values.web.hostAliases }}
      hostAliases: {{- toYaml .Values.web.hostAliases | nindent 6 }}
      {{- end }}
      {{- if .Values.web.nodeSelector }}
      nodeSelector: {{- toYaml .Values.web.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.web.affinity }}
      affinity: {{- toYaml .Values.web.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.web.tolerations }}
      tolerations: {{- toYaml .Values.web.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.web.volumes }}
      volumes: {{- toYaml .Values.web.volumes | nindent 6 }}
      {{- end }}
{{- end }}
