{{- if or .Values.api.env .Values.global.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "api" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "api")) | nindent 4 }}
data:
  {{- if .Values.global.env -}}
  {{- include "helper.env" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.api.env -}}
  {{- include "helper.env" .Values.api | indent 2 }}
  {{- end -}}
{{- end -}}
