apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template.api.fullname" . }}
  labels:
    {{- include "template.api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "template.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "template.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if and .Values.imageCredentials.username .Values.imageCredentials.password }}
      imagePullSecrets:
      - name: {{ include "template.name" . }}-pullsecret
      {{- end }}
      serviceAccountName: {{ include "template.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          {{- if or .Values.api.container.env .Values.api.container.secrets }}
          envFrom:
          {{- if .Values.api.container.env }}
          - configMapRef:
              name: {{ include "template.api.fullname" . }}
          {{- end }}
          {{- if .Values.api.container.secrets }}
          - secretRef:
              name: {{ include "template.api.fullname" . }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.api.container.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.api.container.port }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
