{{- if not .Values.api.statefulset }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "api" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "api")) | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.api.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "api") | nindent 6 }}
  strategy:
    type: {{ .Values.api.strategy.type }}
    {{- if eq .Values.api.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.api.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.api.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      {{- if or .Values.api.podAnnotations .Values.api.secrets .Values.api.env .Values.global.env .Values.global.secrets }}
      annotations:
        {{- include "helper.checksum" (list $ "/api/configmap.yaml") | nindent 8 }}
        {{- include "helper.checksum" (list $ "/api/secret.yaml") | nindent 8 }}
        {{- if .Values.api.podAnnotations }}
        {{- toYaml .Values.api.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels: {{- include "helper.labels" (dict "root" . "componentName" "api") | nindent 8 }}
        {{- if .Values.api.podLabels }}
        {{- toYaml .Values.api.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.api.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.api.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if (get .Values "api").serviceAccount.enabled }}
      serviceAccountName: {{ .Values.api.serviceAccount.name | default (printf "%s-%s" (include "helper.fullname" .) "api") }}
      {{- end }}
      {{- if .Values.api.podSecurityContext }}
      securityContext: {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if or .Values.api.migrate.enabled .Values.api.initContainers }}
      initContainers:
      {{- if .Values.api.migrate.enabled }}
      - name: migrate
        image: "{{ .Values.global.imageRegistry | default .Values.api.migrate.registry }}/{{ .Values.api.migrate.repository }}:{{ .Values.api.migrate.tag | default .Chart.AppVersion }}"
        {{- if .Values.api.env }}
        env: {{- include "helper.env.map-to-array" .Values.api.env | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.api.initContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      containers:
      - name: api
        {{- if .Values.api.securityContext }}
        securityContext: {{- toYaml .Values.api.securityContext | nindent 10 }}
        {{- end }}
        image: "{{ .Values.global.imageRegistry | default .Values.api.image.registry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        {{- if .Values.api.command }}
        command:
        {{- range .Values.api.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.api.args }}
        args:
        {{- range .Values.api.args }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.api.containerPort }}
          name: {{ .Values.api.containerPortName | default "http" }}
          protocol: TCP
        {{- if .Values.api.metrics.enabled }}
        - containerPort: {{ .Values.api.metrics.service.targetPort }}
          name: metrics
          protocol: TCP
        {{- end }}
        {{- if .Values.api.extraPorts }}
          {{- toYaml .Values.api.extraPorts | nindent 8 }}
        {{- end }}
        {{- if or .Values.api.envCm .Values.global.envCm .Values.api.envSecret .Values.global.envSecret .Values.api.envFrom }}
        envFrom:
        {{- if or .Values.api.envCm .Values.global.envCm }}
        - configMapRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "api" }}
        {{- end }}
        {{- if or .Values.api.envSecret .Values.global.envSecret }}
        - secretRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "api" }}
        {{- end }}
        {{- if .Values.api.envFrom }}
          {{- toYaml .Values.api.envFrom | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.api.env }}
        env: {{- include "helper.env.map-to-array" .Values.api.env | nindent 8 }}
        {{- end -}}
        {{- if .Values.api.probes.startupProbe }}
        startupProbe: {{- toYaml .Values.api.probes.startupProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.api.probes.readinessProbe }}
        readinessProbe: {{- toYaml .Values.api.probes.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.api.probes.livenessProbe }}
        livenessProbe: {{- toYaml .Values.api.probes.livenessProbe | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.api.resources | nindent 10 }}
        {{- if .Values.api.volumeMounts }}
        volumeMounts: {{- toYaml .Values.api.volumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.api.extraContainers }}
        {{- tpl (toYaml .Values.api.extraContainers) . | nindent 6 }}
      {{- end }}
      {{- if .Values.api.hostAliases }}
      hostAliases: {{- toYaml .Values.api.hostAliases | nindent 6 }}
      {{- end }}
      {{- if .Values.api.nodeSelector }}
      nodeSelector: {{- toYaml .Values.api.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.api.affinity }}
      affinity: {{- toYaml .Values.api.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.api.tolerations }}
      tolerations: {{- toYaml .Values.api.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.api.volumes }}
      volumes: {{- toYaml .Values.api.volumes | nindent 6 }}
      {{- end }}
{{- end }}
