{{- if and .Values.api.image.credentials.username .Values.api.image.credentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template.api.fullname" . }}-pullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "template.api.imagePullSecret" . }}
{{- end }}
