{{- if .Values.api.container.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "template.api.fullname" . }}
  labels: {{- include "template.api.labels" . | nindent 4 }}
data: {{- include "template.containerSecret" .Values.api.container | indent 2 }}
{{- end -}}
