{{- if or .Values.api.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "template.api.fullname" . }}
  labels: {{- include "template.api.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "template.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.api.secrets -}}
  {{- include "template.secret" .Values.api | indent 2 }}
  {{- end -}}
{{- end -}}
