{{- if and .Values.api.serviceAccount.enabled .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name | default (printf "%s-%s" (include "helper.fullname" .) "api") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "api")) | nindent 4 }}
  {{- if .Values.api.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .Values.api.serviceAccount.annotations) . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.api.serviceAccount.automountServiceAccountToken }}
{{- end }}
