name: Clean cache

on:
  # pull_request:
  #   types:
  #   - closed
  workflow_dispatch:
    inputs:
      PR_NUMBER:
        description: ID number of the pull request associated with the cache
        required: false
        type: number
      BRANCH_NAME:
        description: Branch name associated with the cache
        required: false
        type: string
      CLEAN_IMAGES:
        description: Delete images from ghcr.io
        required: false
        type: boolean
        default: false

permissions:
  packages: write
  contents: read
  actions: write

jobs:
  cleanup-cache:
    uses: this-is-tobi/github-workflows/.github/workflows/clean-cache.yml@v0
    permissions:
      packages: write
      contents: read
      actions: write
    with:
      PR_NUMBER: ${{ github.event.pull_request.number || inputs.PR_NUMBER || 0 }}
      BRANCH_NAME: ${{ inputs.BRANCH_NAME || '' }}
      CLEAN_GH_CACHE: true

  cleanup-images:
    uses: this-is-tobi/github-workflows/.github/workflows/clean-cache.yml@v0
    if: ${{ vars.CLEAN_IMAGES == 'true' || inputs.CLEAN_IMAGES }}
    permissions:
      packages: write
      contents: read
      actions: write
    strategy:
      matrix:
        image:
        - api
        - api-migrate
        - docs
        - cli
        - mcp
    with:
      IMAGE: ghcr.io/${{ github.repository }}/${{ matrix.image }}:pr-${{ github.event.pull_request.number || inputs.PR_NUMBER }}
      CLEAN_GH_CACHE: false
      CLEAN_GHCR_IMAGE: true
