name: Preview comment

on:
  # pull_request:
  #   types:
  #   - labeled
  #   branches:
  #   - "**"
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  preview:
    uses: this-is-tobi/github-workflows/.github/workflows/preview-comment.yml@v0
    permissions:
      pull-requests: write
    with:
      SERVICES: >-
        {
          "API": "${{ vars.API_TEMPLATE_URL }}",
          "Docs": "${{ vars.DOCS_TEMPLATE_URL }}"
        }
      PR_NUMBER: ${{ github.event.pull_request.number }}
      LABEL: preview
